# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_auto_20161130_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humidity',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
